# Generated by Django 5.1.1 on 2024-12-20 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='cuerpo',
        ),
    ]
