# Generated by Django 5.1.1 on 2024-12-17 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0002_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='año',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
