# Generated by Django 5.1.1 on 2024-12-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0003_remove_pelicula_año_pelicula_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(),
        ),
    ]
