# Generated by Django 5.1.1 on 2024-12-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0004_pelicula_portada_alter_pelicula_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(default='portadas/default_portada.jpg', upload_to='portadas/'),
        ),
    ]
