# Generated by Django 5.1.1 on 2024-12-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0005_pelicula_sinopsis_alter_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(blank=True, help_text='Duración en minutos', null=True),
        ),
    ]
