# Generated by Django 5.1.1 on 2024-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0006_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, help_text='Duración en horas y minutos', max_length=50, null=True),
        ),
    ]
