# Generated by Django 5.1.1 on 2024-12-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0007_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='vistas',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='vistas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serie',
            name='puntuacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='serie',
            name='sinopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
