# Generated by Django 5.1.1 on 2024-12-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0008_remove_pelicula_vistas_remove_serie_vistas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='portada',
            field=models.ImageField(default='portadas/default_portada.jpg', upload_to='portadas/'),
        ),
    ]
