# Generated by Django 5.1.1 on 2024-12-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0009_serie_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='portada',
            field=models.ImageField(default='portadas/default_portada.jpg', upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='stream',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
