# Generated by Django 5.1.1 on 2024-12-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_play', '0011_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contenido',
        ),
    ]
